export const en = {
  startOver: "Start Over",
  credit: "Credit : Emin Hosseini .M",
  poweredBy: "Powered By Gemini",

  customizeImage: "Customize Your Image",
  customizeImageDesc: "Select from the options below, or write your own prompt.",
  or: "Or",
  customPromptLabel: "Write Your Own Prompt",
  customPromptPlaceholder: "e.g., A photo of the person as a medieval knight in a castle",
  generateImage: "Generate Image",
  generating: "Generating...",

  dragAndDrop: "Drag & Drop your selfie here",
  browseFiles: "Browse Files",
  supportedFormats: "PNG, JPG, WEBP supported",
  changeImage: "Change Image",
  download: "Download",
  
  original: "Original",
  generated: "Generated",
  generatedImagePlaceholder: "Your styled image will appear here",

  loaderText: "Styling your selfie...",

  error_upload: "Please upload an image first.",
  error_generate: "Failed to generate image. Please try again.",

  hairstyle: "Hairstyle",
  outfit: "Outfit",
  headwear: "Headwear",
  footwear: "Footwear",
  environment: "Environment",
  posture: "Posture",
  effect: "Visual Effect",

  option_none: "None",
  option_shortPixieCut: "Short Pixie Cut",
  option_longWavyHair: "Long Wavy Hair",
  option_spikyMohawk: "Spiky Mohawk",
  option_sleekBob: "Sleek Bob",
  option_braidedCrown: "Braided Crown",
  option_curlyAfro: "Curly Afro",
  option_manBun: "Man Bun",
  option_undercut: "Undercut",
  option_wolfCut: "Wolf Cut",
  option_butterflyCut: "Butterfly Cut",
  option_curtainBangs: "Curtain Bangs",
  option_slickedBack: "Slicked Back",

  option_blackTieTuxedo: "Black Tie Tuxedo",
  option_elegantBallGown: "Elegant Ball Gown",
  option_modernBusinessSuit: "Modern Business Suit",
  option_hypebeastOutfit: "Hypebeast outfit with hoodie and sneakers",
  option_skaterStyle: "Skater style with baggy jeans and graphic tee",
  option_techwear: "Techwear with cargo pants and jacket",
  option_basketballKit: "Full basketball kit",
  option_yogaOutfit: "Yoga outfit with leggings and top",
  option_runnersGear: "Runner's gear with shorts and tank top",
  option_flapperDress: "Vintage 1920s Flapper Dress",
  option_cyberpunkArmor: "Cyberpunk Armor",
  option_bohemianChic: "Bohemian Chic Maxi Dress",
  option_gothicLolita: "Gothic Lolita Dress",
  option_knightArmor: "Knight Armor",
  option_quietLuxury: "Quiet Luxury - Cashmere & Trousers",
  option_oldMoney: "Old Money - Linen & Chinos",
  option_parisianChic: "Parisian Chic - Trench Coat & Scarf",
  option_tokyoStreetStyle: "Tokyo Street Style - Oversized & Layered",
  option_scandinavianMinimalist: "Scandinavian Minimalist - Neutral Tones",

  option_baseballCap: "Baseball Cap",
  option_beanie: "Beanie",
  option_fedoraHat: "Fedora Hat",
  option_cowboyHat: "Cowboy Hat",
  option_crown: "Crown",
  option_scifiHelmet: "Sci-fi Helmet",
  option_flowerWreath: "Flower Wreath",
  option_beret: "Beret",
  option_bucketHat: "Bucket Hat",
  option_silkHeadscarf: "Silk Headscarf",

  option_hightopSneakers: "High-top Sneakers",
  option_leatherBoots: "Leather Boots",
  option_formalShoes: "Formal Dress Shoes",
  option_highHeels: "High Heels",
  option_sandals: "Sandals",
  option_cyberneticBoots: "Cybernetic Boots",
  option_chunkyLoafers: "Chunky Loafers",
  option_espadrilles: "Espadrilles",
  option_classicWhiteSneakers: "Classic White Sneakers",

  option_futuristicCityscape: "Futuristic Cityscape",
  option_tropicalBeach: "Natural landscape of a lush tropical beach",
  option_cozyLibrary: "Cozy Library",
  option_enchantedForest: "Natural landscape of an enchanted, misty forest",
  option_minimalistStudio: "Minimalist Studio",
  option_steampunkWorkshop: "Steampunk Workshop",
  option_mountainTop: "On a mountain summit with a natural panoramic landscape view",
  option_marsColony: "Mars Colony",
  option_italianRiviera: "Natural landscape of the Italian Riviera coastline",
  option_kyotoCherryBlossom: "Natural landscape of Kyoto during cherry blossom season",
  option_swissAlps: "Natural landscape of a serene Swiss Alps meadow",
  option_santorini: "Natural landscape of a Santorini caldera at sunset",
  option_moroccanSouk: "Amidst the natural architecture of a bustling Moroccan souk",

  option_confidentStance: "Confident Stance",
  option_thoughtfulPose: "Thoughtful Pose",
  option_dynamicActionJump: "Dynamic Action Jump",
  option_relaxedLounging: "Relaxed Lounging",
  option_heroicPose: "Heroic Pose",
  option_elegantCurtsy: "Elegant Curtsy",
  option_floating: "Floating/Levitating",
  option_candidLaugh: "Candid laughing pose",
  option_fashionEditorialPose: "Fashion magazine editorial pose",
  option_leaningOnWall: "Leaning against a wall casually",
  
  option_retroFilter: "Retro Filter",
  option_cinematicLighting: "Cinematic Lighting",
  option_watercolorPainting: "Watercolor Painting",
  option_neonGlow: "Neon Glow",
  option_doubleExposure: "Double Exposure",
  option_glitchArt: "Glitch Art",
  option_pencilSketch: "Pencil Sketch",
  option_goldenHour: "Golden hour sunlight effect",
  option_softFocus: "Soft focus dream-like effect",
  option_filmNoir: "Black and white film noir effect",
};

export type Translations = typeof en;