import { Translations } from './en';

export const fa: Translations = {
  startOver: "شروع مجدد",
  credit: "اعتبار : امین حسینی .M",
  poweredBy: "قدرت گرفته از Gemini",

  customizeImage: "سفارشی‌سازی تصویر",
  customizeImageDesc: "از گزینه‌های زیر انتخاب کنید یا دستور خود را بنویسید.",
  or: "یا",
  customPromptLabel: "دستور خود را بنویسید",
  customPromptPlaceholder: "مثال: عکسی از شخص به عنوان شوالیه قرون وسطایی",
  generateImage: "تولید تصویر",
  generating: "در حال تولید...",

  dragAndDrop: "سلفی خود را اینجا بکشید و رها کنید",
  browseFiles: "انتخاب فایل",
  supportedFormats: "پشتیبانی از PNG, JPG, WEBP",
  changeImage: "تغییر تصویر",
  download: "دانلود",
  
  original: "اصلی",
  generated: "تولید شده",
  generatedImagePlaceholder: "تصویر استایل‌دار شما اینجا نمایش داده می‌شود",

  loaderText: "در حال استایل دادن به سلفی...",

  error_upload: "لطفا ابتدا یک تصویر آپلود کنید.",
  error_generate: "تولید تصویر ناموفق بود. دوباره تلاش کنید.",

  hairstyle: "مدل مو",
  outfit: "لباس",
  headwear: "کلاه و سرپوش",
  footwear: "کفش",
  environment: "محیط",
  posture: "ژست",
  effect: "جلوه بصری",

  option_none: "هیچکدام",
  option_shortPixieCut: "پیکسی کوتاه",
  option_longWavyHair: "موی بلند و موج‌دار",
  option_spikyMohawk: "موهیکان سیخ‌سیخی",
  option_sleekBob: "باب صاف",
  option_braidedCrown: "تاج بافتنی",
  option_curlyAfro: "آفروی فرفری",
  option_manBun: "گوجه‌ای مردانه",
  option_undercut: "آندرکات",
  option_wolfCut: "مدل موی ولف کات",
  option_butterflyCut: "مدل موی پروانه‌ای",
  option_curtainBangs: "چتری پرده‌ای",
  option_slickedBack: "موی صاف شده به عقب",

  option_blackTieTuxedo: "تاکسیدو رسمی",
  option_elegantBallGown: "لباس مجلسی شیک",
  option_modernBusinessSuit: "کت و شلوار مدرن",
  option_hypebeastOutfit: "استایل هایپ‌بیست با هودی و کتانی",
  option_skaterStyle: "استایل اسکیت‌باز با شلوار گشاد و تیشرت طرح‌دار",
  option_techwear: "پوشاک تکنیکی با شلوار کارگو و ژاکت",
  option_basketballKit: "لباس کامل بسکتبال",
  option_yogaOutfit: "لباس یوگا با لگ و تاپ",
  option_runnersGear: "لباس دوندگی با شورت و تاپ",
  option_flapperDress: "لباس فلاپر وینتیج دهه ۱۹۲۰",
  option_cyberpunkArmor: "زره سایبرپانک",
  option_bohemianChic: "لباس ماکسی شیک بوهمی",
  option_gothicLolita: "لباس لولیتا گوتیک",
  option_knightArmor: "زره شوالیه",
  option_quietLuxury: "لاکچری آرام - پلیور کشمیر و شلوار پارچه‌ای",
  option_oldMoney: "استایل اشرافی - پیراهن کتان و شلوارک چینو",
  option_parisianChic: "شیک پاریسی - بارانی، پیراهن راه‌راه و شال",
  option_tokyoStreetStyle: "استایل خیابانی توکیو - لایه‌های گشاد و اکسسوری",
  option_scandinavianMinimalist: "مینیمال اسکاندیناوی - رنگ‌های خنثی",

  option_baseballCap: "کلاه بیسبال",
  option_beanie: "کلاه بافتنی",
  option_fedoraHat: "کلاه فدورا",
  option_cowboyHat: "کلاه کابوی",
  option_crown: "تاج",
  option_scifiHelmet: "کلاه علمی-تخیلی",
  option_flowerWreath: "تاج گل",
  option_beret: "کلاه بره",
  option_bucketHat: "کلاه باکت",
  option_silkHeadscarf: "روسری ابریشمی",

  option_hightopSneakers: "کتانی ساق‌بلند",
  option_leatherBoots: "بوت چرمی",
  option_formalShoes: "کفش رسمی",
  option_highHeels: "کفش پاشنه‌بلند",
  option_sandals: "صندل",
  option_cyberneticBoots: "بوت سایبرنتیک",
  option_chunkyLoafers: "لوفرهای درشت",
  option_espadrilles: "اسپادریل",
  option_classicWhiteSneakers: "کتانی سفید کلاسیک",

  option_futuristicCityscape: "منظره شهری آینده‌نگر",
  option_tropicalBeach: "منظره طبیعی یک ساحل استوایی سرسبز",
  option_cozyLibrary: "کتابخانه دنج",
  option_enchantedForest: "منظره طبیعی یک جنگل جادویی و مه‌آلود",
  option_minimalistStudio: "استودیو مینیمالیستی",
  option_steampunkWorkshop: "کارگاه استیم‌پانک",
  option_mountainTop: "بر فراز قله کوه با منظره طبیعی پانوراما",
  option_marsColony: "کلونی مریخ",
  option_italianRiviera: "منظره طبیعی سواحل ریویرای ایتالیا",
  option_kyotoCherryBlossom: "منظره طبیعی کیوتو در فصل شکوفه‌های گیلاس",
  option_swissAlps: "منظره طبیعی یک چمنزار آرام در آلپ سوئیس",
  option_santorini: "منظره طبیعی کالدرای سانتورینی هنگام غروب",
  option_moroccanSouk: "در میان معماری طبیعی یک بازار مراکشی شلوغ",

  option_confidentStance: "ژست با اعتماد به نفس",
  option_thoughtfulPose: "ژست متفکرانه",
  option_dynamicActionJump: "پرش اکشن پویا",
  option_relaxedLounging: "لمیده و آرام",
  option_heroicPose: "ژست قهرمانانه",
  option_elegantCurtsy: "تعظیم مودبانه",
  option_floating: "شناور/معلق",
  option_candidLaugh: "ژست خنده خودمانی",
  option_fashionEditorialPose: "ژست سرمقاله مجله مد",
  option_leaningOnWall: "تکیه دادن راحت به دیوار",
  
  option_retroFilter: "فیلتر رترو",
  option_cinematicLighting: "نورپردازی سینمایی",
  option_watercolorPainting: "نقاشی آبرنگ",
  option_neonGlow: "درخشش نئونی",
  option_doubleExposure: "نوردهی دوگانه",
  option_glitchArt: "هنر گلیچ",
  option_pencilSketch: "طراحی با مداد",
  option_goldenHour: "جلوه نور خورشید ساعت طلایی",
  option_softFocus: "جلوه فوکوس نرم رویایی",
  option_filmNoir: "جلوه فیلم نوآر سیاه و سفید",
};
